config/routes.rb
Rails.application.routes.draw do
  resources :departamentos
  resources :produtos, only: [:new, :create, :destroy, :edit, :update]
  get "/produtos/busca" => "produtos#busca", as: :busca_produto
  root 'produtos#index'
  # post '/produtos' => 'produtos#create'
  # get '/produtos/new' => 'produtos#new'
  # delete '/produtos/:id' => 'produtos#destroy', as: :produto
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/departamento.rb
class Departamento < ApplicationRecord
end

app/models/produto.rb
class Produto < ApplicationRecord
  belongs_to :departamento
  
  validates :quantidade, :departamento, presence: true
  validates :nome, length: {minimum:5}
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/departamentos_controller.rb
class DepartamentosController < ApplicationController
  before_action :set_departamento, only: %i[ show edit update destroy ]

  # GET /departamentos or /departamentos.json
  def index
    @departamentos = Departamento.all
  end

  # GET /departamentos/1 or /departamentos/1.json
  def show
    @produtos_por_departamento = Produto.where("departamento_id = ?", params[:id]
    )
  end

  # GET /departamentos/new
  def new
    @departamento = Departamento.new
  end

  # GET /departamentos/1/edit
  def edit
  end

  # POST /departamentos or /departamentos.json
  def create
    @departamento = Departamento.new(departamento_params)

    respond_to do |format|
      if @departamento.save
        format.html { redirect_to departamentos_path, notice: "Departamento was successfully created." }
        format.json { render :show, status: :created, location: @departamento }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @departamento.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /departamentos/1 or /departamentos/1.json
  def update
    respond_to do |format|
      if @departamento.update(departamento_params)
        format.html { redirect_to @departamento, notice: "Departamento was successfully updated." }
        format.json { render :show, status: :ok, location: @departamento }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @departamento.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /departamentos/1 or /departamentos/1.json
  def destroy
    @departamento.destroy
    respond_to do |format|
      format.html { redirect_to departamentos_url, notice: "Departamento was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_departamento
      @departamento = Departamento.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def departamento_params
      params.require(:departamento).permit(:nome)
    end
end

app/controllers/produtos_controller.rb
class ProdutosController < ApplicationController
  before_action :set_produto, only: [:edit, :update, :destroy]
  def index
    @produtos_por_nome = Produto.order(:nome).limit 10
    @produtos_por_preco = Produto.order(:preco).limit 2
  end

  def new
    @produto = Produto.new
    renderiza :new
  end

  def busca
    @nome_a_buscar = params[:nome]
    @produtos = Produto.where "nome like ?", "%#{@nome_a_buscar}%"
  end

  def create
    @produto = Produto.new produto_params
    @produto.save
    if @produto.save
      flash[:notice] = "Produto salvo com sucesso!"
      redirect_to root_url
    else
      renderiza :new
    end
  end

  def destroy
    @produto.destroy
    redirect_to root_url
  end

  def edit
    renderiza :edit
  end

  def update
    if @produto.update produto_params
      flash[:notice] = "Produto atualizado com sucesso!"
      redirect_to root_url
    else
      renderiza :edit
    end
  end

  private

  def renderiza(view)
    @departamentos = Departamento.all
    render view
  end

  def set_produto
    id = params[:id]
    @produto = Produto.find(id)
  end

  def produto_params
    params.require(:produto).permit(:nome, :descricao, :quantidade, :preco, :departamento_id)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/departamentos_helper.rb
module DepartamentosHelper
end

app/helpers/produtos_helper.rb
module ProdutosHelper
end

app/views/departamentos/_form.html.erb
<%= form_with(model: departamento) do |form| %>
  <% if departamento.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(departamento.errors.count, "error") %> prohibited this departamento from being saved:</h2>

      <ul>
        <% departamento.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= form.label :nome %>
    <%= form.text_field :nome %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/departamentos/edit.html.erb
<h1>Editing Departamento</h1>

<%= render 'form', departamento: @departamento %>

<%= link_to 'Voltar', departamentos_path %>

app/views/departamentos/index.html.erb
<% if notice %>
  <div class="alert alert-success" role="alert">
    <p id="notice"><%= notice %></p>
  </div>
<% end %>

<div>  
  <table class="table table-bordered table-striped table-hover">
    <thead>
      <tr>
        <th>Nome</th>
        <th colspan="3"></th>
      </tr>
    </thead>
    <tbody>
      <% @departamentos.each do |departamento| %>
        <tr>
          <td><%= departamento.nome %></td>
          <td><%= button_to 'Ver Produtos', departamento, method: :get, class: "btn btn-primary"  %></td>
          <td><%= button_to 'Alterar', edit_departamento_path(departamento), method: :get, class: "btn btn-default" %></td>
          <td><%= button_to 'Remover', departamento, method: :delete, class: "btn btn-danger", data: { confirm: "Tem certeza que deseja remover o departamento #{departamento.nome}?" } %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
<div>
<br>
<%= link_to 'Novo Departamento', new_departamento_path %>

app/views/departamentos/new.html.erb
<h1>New Departamento</h1>

<%= render 'form', departamento: @departamento %>

<%= link_to 'Back', departamentos_path %>

app/views/departamentos/show.html.erb
<p id="notice"><%= notice %></p>

<div>  
  <table class="table table-bordered table-striped table-hover">
    <thead>
      <tr>
        <th>Nome</th>
        <th>Descrição</th>
        <th>Departamento</th>
        <th>Preço</th>
      </tr>
    </thead>
    <tbody>
      <%= render @produtos_por_departamento %>
    </tbody>
  </table>
<div>
<%= link_to 'Voltar', departamentos_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Loja de Camisetas</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= nav_bar brand: "Loja", brand_link: root_url do %>
      <%= menu_group do %>
        <%= menu_item "Produtos", root_path %>
        <%= menu_item "Departamentos", departamentos_path %>
      <% end %>
      <%= form_tag busca_produto_path, method: :get, class: "navbar-form navbar-right" do %>
        <div class="form-group">
          <%= text_field_tag :nome, @nome_a_buscar, class: "form-control" %>
          <%= button_to "Buscar", nil, class: "btn btn-default" %>
        </div>
      <% end %>      
    <% end %>
    <div class="container">
      <%= yield %>
    </div>
  </body>
</html>

app/views/produtos/_form.html.erb
<% @produto.errors.full_messages.each do |message| %>
  <div class="alert alert-danger" role="alert">
    <%= message %>
  </div>
<% end %>

<%= form_for @produto do |f| %>
  <div class="form-group">
    <%= f.label :nome, 'Nome: ' %>
    <%= f.text_field :nome, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= f.label :descricao, 'Descrição: ' %>
    <%= f.text_area :descricao,  class: "form-control", rows: 4 %>
  </div>
  
  <div class="form-group">
    <%= f.label :departamento, 'Departamento' %>
    <%= f.collection_select :departamento_id, @departamentos, :id, :nome, {}, class: "form-control" %>
  </div>

  <div class="form-inline">
    <div class="form-group">
      <%= f.label :preco, 'Preço: ' %>
      <%= f.number_field :preco, step: 0.01,  class: "form-control" %>
    </div>
    <div class="form-group">
      <%= f.label :quantidade, 'Quantidade: ' %>
      <%= f.number_field :quantidade, step: 1,  class: "form-control" %>
    </div>
    <div>
      <%= f.submit acao, class: "btn btn-primary form-control" %>
    </div>
  </div>
  <%= link_to 'Voltar', root_path %>

<% end %>

app/views/produtos/_produto.html.erb
<tr>
  <td><%= produto.nome %></td>
  <td><%= produto.descricao %></td>
  <% if produto.departamento %>
    <td><%= produto.departamento.nome %></td>
  <% else %>
    <td></td>
  <% end %>
  <td><%= produto.preco %></td>
  <td><%= link_to "Alterar", edit_produto_path(produto), class: "btn btn-default"%></td>
  <td><%= button_to "Remover", produto, method: :delete, class: "btn btn-danger", data: { confirm: "Tem certeza que deseja remover #{produto.nome}?"} %></td>
</tr>

app/views/produtos/busca.html.erb
<div>  
  <table class="table table-bordered table-striped table-hover">
    <thead>
      <tr>
        <th>Nome</th>
        <th>Descrição</th>
        <th>Preço</th>
      </tr>
    </thead>
    <tbody>
      <%= render @produtos %>
    </tbody>
  </table>
<div>

app/views/produtos/edit.html.erb
<%= render partial: 'form', locals: {acao: 'Atualizar o produto'} %>

app/views/produtos/index.html.erb
<% if flash[:notice] %>
  <div class="alert alert-success" role="alert">
    <%= flash[:notice] %>
  </div>
<% end %>
<div>  
  <table class="table table-bordered table-striped table-hover">
    <thead>
      <tr>
        <th>Nome</th>
        <th>Descrição</th>
        <th>Departamento</th>
        <th>Preço</th>
      </tr>
    </thead>
    <tbody>
      <%= render @produtos_por_nome %>
    </tbody>
  </table>
<div>
  <table class="table table-bordered table-striped table-hover">
    <thead>
      <tr>
        <th>Nome</th>
        <th>Descrição</th>
        <th>Departamento</th>
        <th>Preço</th>
      </tr>
    </thead>
    <tbody>
      <%= render @produtos_por_preco %>
    </tbody>
  </table>
  <br>
  <%= link_to "Criar novo produto", new_produto_path %>
</div>

app/views/produtos/new.html.erb
<%= render partial: 'form', locals: {acao: 'Criar o produto'} %>